apiVersion: v1
kind: Service
metadata:
  name: localstack
  labels:
    app: localstack
spec:
  type: NodePort
  selector:
    app: localstack
  ports:
  - name: http
    port: 4566
    targetPort: 4566
    nodePort: 30456
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: localstack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: localstack
  template:
    metadata:
      labels:
        app: localstack
    spec:
      containers:
      - name: localstack
        image: localstack/localstack:3.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4566
        env:
        - name: SERVICES
          value: "s3,sqs,iam"
        - name: DEBUG
          value: "1"
        - name: ACTIVATE_PRO
          value: "0"
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
